plugins {
    id 'net.fabricmc.fabric-loom' version '1.16-SNAPSHOT'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    accessWidenerPath = file("src/main/resources/affogato_core.accesswidener")
}

repositories {
    maven { url = "https://maven.parchmentmc.org" }
    maven { url = "https://maven.terraformersmc.com/" }
    maven { url = "https://maven.fzzyhmstrs.me/" }
    maven { url = "https://jitpack.io" }
    maven { url = "https://maven.blamejared.com/" }
    maven { url = "https://maven.cassian.cc" }
    maven { url = "https://maven.caffeinemc.net/releases" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
    implementation "me.fzzyhmstrs:fzzy_config:${project.fzzy_version}"
    include(implementation("com.moulberry:mixinconstraints:${project.mixinconstraints_version}"))
    implementation(include("com.github.ramixin:mixson-fabric:${project.mixson_version}")) {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }

    runtimeOnly "net.caffeinemc:sodium-fabric:0.8.9+mc26.1.1"

    compileOnly "maven.modrinth:farmers-delight-refabricated:26.1-3.5.1"
    compileOnly "maven.modrinth:appleskin:3.0.9+mc26.1"
    compileOnly "maven.modrinth:wilder-wild:4.2.8-mc26.1"
    compileOnly "maven.modrinth:trailier-tales:1.2.5-mc26.1"
    compileOnly "maven.modrinth:better-block-entities:1.3.2+mc26.1.2"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

publishMods {
    file = jar.archiveFile
    changelog = file(getRootDir().path + "/CHANGELOG.md").text
    type = STABLE
    modLoaders.add("fabric")
    displayName = project.mod_version + " for " + project.minecraft_version

    modrinth {
        accessToken = providers.environmentVariable("MR_KEY")
        projectId = "Q8yzjHI3"
        minecraftVersions.add(project.minecraft_version)
        minecraftVersions.add("26.1.1")
        minecraftVersions.add("26.1")
        requires("fabric-api", "fzzy-config")
        optional("modmenu")
    }
}