plugins {
    id 'fabric-loom' version '1.11-SNAPSHOT'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    accessWidenerPath = file("src/main/resources/affogatotweaks.accesswidener")
}

repositories {
    maven { url = "https://maven.parchmentmc.org" }
    maven { url = "https://maven.wispforest.io" }
    maven { url = "https://jitpack.io" }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.parchment_version}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    include(implementation("com.moulberry:mixinconstraints:${project.mixinconstraints_version}"))
    modImplementation(include("com.github.ramixin:mixson-fabric:${project.mixson_version}")) {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-api"
    }
    modImplementation(include("maven.modrinth:custombrewrecipes:1.3.2"))
    modImplementation "io.wispforest:lavender:${project.lavender_version}"

    modImplementation "maven.modrinth:iris:1.8.8+1.21.1-fabric"
    modCompileOnly "maven.modrinth:farmers-delight-refabricated:1.21.1-3.1.2"
    modRuntimeOnly "maven.modrinth:euphoria-patches:1.6.5-r5.5.1-fabric"
    modRuntimeOnly "maven.modrinth:sodium:mc1.21.1-0.6.13-fabric"
    modRuntimeOnly "maven.modrinth:worldedit:7.3.8"
    modRuntimeOnly "org.antlr:antlr4-runtime:4.13.1"
    modRuntimeOnly "io.github.douira:glsl-transformer:2.0.1"
    modRuntimeOnly "org.anarres:jcpp:1.4.14"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

def targetJavaVersion = 21
tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}