org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
loader_version=0.19.2
minecraft_version=26.1.2
mod_version=26.1.13
maven_group=me.pajic
archives_base_name=affogato_core
fabric_version=0.147.0+26.1.2
mixinconstraints_version=1.1.0
mixson_version=v2.1.0
modmenu_version=18.0.0-alpha.8
fzzy_version=0.7.6+26.1-pre-3
sodium_version=0.8.10+mc26.1.2